### ISSUE TITLE
Google changed, Static Google is covering some result

### ISSUE THREAD

**Issue by p1nkyy** [tumpio/gmscripts#24]
Hello @tumpio , Google changed and as a result, Static Google is covering a bit of the result on the left side. Please help fix.

**Comment by tumpio** [comment]
Hi @p1nkyy, can you post a screen shot. I noticed some issues too, but right now seems to be working again. Maybe I'm not getting the new Google page.

**Comment by p1nkyy** [comment]
![screenshot-www google com-2020 03 08-20_19_25](https://user-images.githubusercontent.com/7593831/76163613-2998b700-617a-11ea-82a5-d891a225fe6d.jpg)
Here you go, let me know if you need the saved webpage like last time!

**Comment by tumpio** [comment]
Fixed! Released a new versions to AMO (still not yet reviewed): https://addons.mozilla.org/fi/firefox/addon/googlestatic/

Also updated the Userscript
https://openuserjs.org/scripts/tumpio/Static_Google

and Userstyle versions:
https://userstyles.org/styles/99153/google-static

**Comment by p1nkyy** [comment]
Thank you as usual for the fast update!
