### ISSUE TITLE
[Endless Google] Duplicate Data [Bug]

### ISSUE THREAD

**Issue by innateessence** [tumpio/gmscripts#28]
The first time this script populates additional elements into the DOM to provide endless scrolling, it appears to behave as expected, however, every time after that it's populating the DOM with duplicate content.

**Comment by nanderer** [comment]
please give more details (browse version, userscript addon, script version, other addons, etc.), here it is working fine (firefox esr with tampermonkey) so it can be reproduced

**Comment by innateessence** [comment]
Sorry, I no longer use this. Closing.

I was using Google Chrome + Tamper monkey. Anything beyond that I'm unaware of. Sorry.
