### ISSUE TITLE
Static Google is broken

### ISSUE THREAD

**Issue by p1nkyy** [tumpio/gmscripts#4]
Broken today (02/26). Overlapping with Google+ stuff (Profile Picture, Notification icons, etc)
Here's a screenshot: http://puu.sh/gdBdb/a8649d2930.jpg

**Comment by BioHaZard1** [comment]
Pushed a fix to tumpio, should fix the latest change.

**Comment by p1nkyy** [comment]
Where @BioHaZard1 ?

**Comment by BioHaZard1** [comment]
Not sure where its gone? But if you're using the CSS version you can change "hdtb_more_mn" to "hdtb_more". Looks like Google changed the tag.

**Comment by p1nkyy** [comment]
Thanks, it works!

**Comment by p1nkyy** [comment]
@BioHaZard1 Broken again today. The words are overlapping with each other. Can you help me again?

**Comment by tumpio** [comment]
Google decided to change the selector naming scheme, (from "_" to "-").

@p1nkyy Sorry that you had to wait this long :(
@BioHaZard1 Thank you for your help, I appreciate it!

**Comment by p1nkyy** [comment]
Yayy, finally! Thanks, @tumpio. Had a friend who understand scripts to fork this but the end result is not quite similar to yours.

**Comment by p1nkyy** [comment]
Broken again today, as per May 17. Please fix @tumpio . Thanks before!

**Comment by tumpio** [comment]
It seems to work for me. What is broken @p1nkyy ?

**Comment by p1nkyy** [comment]
Oh yeah, never mind, sorry, it was acting strange earlier, lol :grin:

**Comment by hamid914** [comment]
Static Google is not working on Tampermonkey installed on my Safari. It does not change anything on google search page. Instead, using the [CSS style](http://userstyles.org/styles/99153.css) in Stylish installed on my Safari changes the style (although there are bugs in this transformation).

Why the script can't apply the stylesheet file?

**Comment by tumpio** [comment]
Did it work on Tampermonkey before the update?

> (although there are bugs in this transformation).

Can you list all of them, I will try to fix. I update the style to support the new Google layout.

**Comment by hamid914** [comment]
@tumpio I tried Static Google 2 month ago for the first time. The JS script did not work ever for me on Tampermonkey (but the CSS works on Stylish 1.9.1). I updated Tampermonkey to 4.2.5291 today with Static Google 1.9.0 installed. It does not work on updated Tampermonkey too. I am using Safari 9.1.3 on OS X 10.11.6.

Sorry, I didn't understand "all of them" to list.
If it can be useful, tell me how to get log for you to debug.

**Comment by tumpio** [comment]
Ok, thanks! I will investigate the problem with Tampermonkey.

> Sorry, I didn't understand "all of them" to list.
I mean that what bugs do you have with the user style? Is there something what I can fix?

**Comment by tumpio** [comment]
@hamid914 It should be now fixed!

**Comment by hamid914** [comment]
@tumpio WOW 😮 It works great on version 1.9.4 👍 
Thanks for your support 🌹
